---
title: "Analysis_of_GSE33126_id"
author: "vikram"
date: "03/09/2021"
output:
  html_document: default
  pdf_document: default
---


Need to install the following packages before starting
```{r}
#install.packages("BiocManager")
#install.packages("forcats")
#install.packages("stringr")
#install.packages("ggplot2")
#install.packages("ggrepel")
#install.packages("readr")
#install.packages("tidyr")
#install.packages("survminer")
#BiocManager::install("GEOquery")
#BiocManager::install("limma")
#BiocManager::install("pheatmap")
#BiocManager::install("org.Hs.eg.db")
```

Importing the data

```{r}
library(GEOquery)
## change my_id to be the dataset that you want.
my_id <- "GSE33126"
gse <- getGEO(my_id)
```





```{r}
## check how many platforms used
length(gse)

```

```{r}
gse <- gse[[1]]
gse

```
```{r}
## if more than one dataset is present, you can analyse the other dataset by changing the number inside the [[...]]
## e.g. gse <- gse[[2]]

```

```{r}
pData(gse) ## print the sample information
fData(gse) ## print the gene annotation
exprs(gse) ## print the expression data

```
Check the normalisation and scales used


```{r}
## exprs get the expression levels as a data frame and get the distribution
summary(exprs(gse))
```

```{r}
exprs(gse) <- log2(exprs(gse))
boxplot(exprs(gse),outline=FALSE, col = c("green","yellow","purple"))

```
Inspect the clinical variables

```{r}
library(dplyr)
```

```{r}
sampleInfo <- pData(gse)
sampleInfo
```
```{r}
## source_name_ch1 and characteristics_ch1.1 seem to contain factors we might need for the analysis. Let's pick just those columns

sampleInfo <- select(sampleInfo, source_name_ch1,characteristics_ch1.1)

## Optionally, rename to more convenient column names
sampleInfo <- rename(sampleInfo,group = source_name_ch1, patient=characteristics_ch1.1)
```

```{r}
sampleInfo
```
Sample clustering

```{r}
library(pheatmap)
## argument use="c" stops an error if there are any missing data points

corMatrix <- cor(exprs(gse),use="c")
pheatmap(corMatrix)   
```




